# https://github.com/DepthAnything/Depth-Anything-V2/tree/main/metric_depth#pre-trained-models

encoder: "vitb"
input_size: 518 # default 518
max_depth: 80 # outdoor=80metri, indoor=20metri
model_path: "checkpoints/depth_anything_v2_metric_vkitti_vitb.pth"
